### ISSUE TITLE
non-CSV bdiscriminators 0

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#141]
All other b-discriminators except the standard one are 0: would be useful to fill to benefit from the new cMVAv2 with offline computation: https://github.com/cms-sw/cmssw/pull/10197/

**Comment by arizzi** [comment]
can you make a PR running that on the preprocessor?  you can see example in the 722 version of heppy e.g.
https://github.com/vhbb/cmssw/blob/vhbbHeppy722patch2/VHbbAnalysis/Heppy/test/combined_cmssw.py

**Comment by jpata** [comment]
@arizzi do you think it's reasonable/needed to re-calculate the input taggers using `switchJetCollection` in the preprocessor?

Namely the soft-lepton ones I can't find in MiniAOD: (how to which taggers are there by default?)
The others(proba, BProba, old CSV with AVR) are there with the `pf*` prefix.
Thanks

**Comment by arizzi** [comment]
I would not rerun the switchJetCollection producing the jets but just run the needed btag stuff. @ferencek do you have an example including Soft Lepton stuff? (perhaps it is already in the MiniAOD WorkBook twiki!)

**Comment by ferencek** [comment]
@jpata, taggers stored in MiniAOD are those defined in the default PAT jet configuration, namely `PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cfi.py`.

@arizzi, `switchJetCollection()` does not recluster jets so it could definitely be used to re-run a few missing taggers. However, by default it will also modify `patJets.discriminatorSources` so to get around that one could call `switchJetCollection()` with a limited set of missing taggers and then manually update `patJets.discriminatorSources` with the full list of taggers.

**Comment by ferencek** [comment]
@arizzi, concerning soft leptons, in recent 74X releases they were simply added to `PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cfi.py` but now that I think about it, they would also have to be re-run because otherwise old buggy discriminators could be picked up. So there needs to be something that will call `switchJetCollection()` for at least one jet collection with at least one tagger so that all the default taggers also get loaded and run in the unscheduled mode.

**Comment by ferencek** [comment]
I just tested MiniAOD production in CMSSW_7_4_11_patch1 and since `switchJetCollection()` is called for ak8 and Puppi jets, all the default taggers are loaded and those needed for ak4 jets are also re-run. However, this is not very robust because if someone disabled `switchJetCollection()` calls, slimmed ak4 would not pick up the latest discriminators.

**Comment by arizzi** [comment]
@ferencek we are not talking about miniaod production here but of running on top of miniaod, that's why I'd avoid switchJetCollection that would recreate the patJets and I do not want this...

I'd rather spell the sequence of what we want to run

**Comment by jpata** [comment]
I will try to do it explicitly as Gregor did for the subjets, the code for this is already in the pre-processor.

**Comment by ferencek** [comment]
@arizzi, sorry, I misunderstood then. Defining a sequence by hand is definitely a possibility since any type of jets can be used as input including PAT jets. I don't have an example of this for soft lepton taggers but the same thing for TC and SSV taggers was covered in https://twiki.cern.ch/twiki/bin/viewauth/CMS/SWGuideCMSDataAnalysisSchool2015BTaggingExercise#Configuring_your_own_b_tagging_s

However, there is one detail to keep in mind. In the standard RECO b tagging is run on raw jets but here you would run it on corrected jets. This can lead to small differences in the final discriminator values.

**Comment by jpata** [comment]
@arizzi @ferencek Thanks for the ideas. I actually managed to run the SoftMuon/Electron taggers again in the unscheduled mode, just switching the input jet/lepton/pv collections. Seems to work, testing on a larger scale now...
@arizzi I also re-purposed the `AdditionalBTag.py` analyzer for the new cMVAv2.

**Comment by arizzi** [comment]
please cross check which modules are actually run in the end of cmsrun
summary

**Comment by jpata** [comment]
~~~
TrigReport       2000       2000       2000          0          0 softPFElectronBJetTags
TrigReport       2000       2000       2000          0          0 softPFElectronsTagInfos
TrigReport       2000       2000       2000          0          0 softPFMuonBJetTags
TrigReport       2000       2000       2000          0          0 softPFMuonsTagInfos

TimeReport   0.001378     0.001378     0.001378  softPFElectronBJetTags
TimeReport   0.000296     0.000296     0.000296  softPFElectronsTagInfos
TimeReport   0.000366     0.000366     0.000366  softPFMuonBJetTags
TimeReport   0.000933     0.000933     0.000933  softPFMuonsTagInfos

TimeReport       event loop CPU/event = 0.142847
TimeReport      event loop Real/event = 0.208836
~~~

**Comment by jpata** [comment]
Solved by https://github.com/vhbb/cmssw/pull/170
