### ISSUE TITLE
VtypeSim and genVboson info broken for DY

### ISSUE THREAD

**Issue by jstupak** [vhbb/cmssw#283]
In >5% of DY events in the HT-binned MadGraph ntuples, VtypeSim = -1, and nGenVbosons = nGenLep = 0. This makes it impossible (as far as I can imagine) to correct the pT spectrum of the DY MC for higher order effects in these events.  I looked through the GenParticle info in these events and see that the event record does not contain a Z boson, instead the event record simply contains a dliepton pair as the 5th and 6th particles in the event with an off-Z invariant mass, which causes the current algorithm to fail.

**Comment by arizzi** [comment]
@perrozzi is this effect known? is it happening also in 76X ? Is it a bug in MINIAOD genParticlePruner or just MG not creating those ?

**Comment by perrozzi** [comment]
what I know is that this is (unfortunately) possible in pythia8, so I don't think is a bug.
there is for sure a trick to correctly tag the event by looking at the lhe instead of genparticles, 
but then the only way to reconstruct the kinematic is to look at genparticles (due to isr, fsr, etc).
I am not 100% sure that 5th and 6th is fully general though, would be good to have more info about the checks performed, for instance which samples have been tested?

**Comment by jstupak** [comment]
5th and 6th is probably not fully general.  I was trying not to modify the behavior for other samples.  

I checked and this problem is very small (.5%) in the similar HT-binned Z->nunu samples and non-existent in the HT-binned W+jets.  So I only tested this on the HT-binned Z->ll, verifying that the genVboson p4 was the sum of the gen lepton p4, VtypeSim was set, and genLeps had 2 entries.

What other samples are we concerned about?

**Comment by perrozzi** [comment]
I was wondering about different generators for the same process, but let's keep it like this for the moment. thanks

**Comment by arizzi** [comment]
can we close this or you want to keep track of the need of making that more general?

**Comment by jstupak** [comment]
I think its fine to close it.

**Comment by perrozzi** [comment]
agreed
