### ISSUE TITLE
Scale factors for ele trigger

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#442]
@dcurry09
Could ypu please add the latest ele trigger SF you computed for 76X?
Even if they will change in the future, I would prefer to have them integrated in the code.
Thanks

**Comment by dcurry09** [comment]
Hi Lorenzo,

I am working on this now.  I agree that this is a good idea to have, since
in the future all we have to do is change the JSON for an updated trigger
SF.

Can you tell me what is the correct version of CMSSW 80x to use?  8_0_3 for
example?

thanks,

On Tue, Jun 7, 2016 at 9:10 AM, bianchini notifications@github.com wrote:

> @dcurry09 https://github.com/dcurry09
> Could ypu please add the latest ele trigger SF you computed for 76X?
> Even if they will change in the future, I would prefer to have them
> integrated in the code.
> Thanks
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/vhbb/cmssw/issues/442, or mute the thread
> https://github.com/notifications/unsubscribe/AEJ5ms3d-dFjLQ2jyid_24GMrC_rOb5Dks5qJRlvgaJpZM4Ivn-Q
> .

## 

## David Curry

Physics Department
CERN B8 R-031 || University of Florida, NPB 1218
curry@phys.ufl.edu
076 291 0492

**Comment by bianchini** [comment]
Great! 
Please use 8_0_5

**Comment by bianchini** [comment]
Done by https://github.com/vhbb/cmssw/pull/445.

According to Michele, Ele23 is prescaled now: we must switch to Ele27.
@dcurry09: do you have the 76X SF for Ele27 as well?

**Comment by dcurry09** [comment]
Hi,

No, the electron trigger SF was computed on Ele23 and will have to be
redone for Ele27.  As far as I know the MVAID SF can still be used on
Ele27.  Please correct if this is wrong.

On Thu, Jun 9, 2016 at 8:36 AM, bianchini notifications@github.com wrote:

> Done by #445 https://github.com/vhbb/cmssw/pull/445.
> 
> According to Michele, Ele23 is prescaled now: we must switch to Ele27.
> @dcurry09 https://github.com/dcurry09: do you have the 76X SF for Ele27
> as well?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/vhbb/cmssw/issues/442#issuecomment-224811893, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEJ5mnIQ4fo5MIQX6yWm6QyT51OaIfyZks5qJ7RUgaJpZM4Ivn-Q
> .

## 

## David Curry

Physics Department
CERN B8 R-031 || University of Florida, NPB 1218
curry@phys.ufl.edu
076 291 0492

**Comment by bianchini** [comment]
ID SF are with respect to offline. 

The trigger will be with respect to probes passing the ID, so, yes, the MVAID SF remain the same.
The ttH people have already computed SF for Ele27: try with your ttH friends, otherwise let me know and I will contact other people.

**Comment by azzurrip** [comment]
Hi, I see HLT_Ele25 is also unprescaled, can we use Ele25 ?
Paolo

On 09 Jun 2016, at 09:48, bianchini <notifications@github.com<mailto:notifications@github.com>> wrote:

ID SF are with respect to offline.

The trigger will be with respect to probes passing the ID, so, yes, the MVAID SF remain the same.
The ttH people have already computed SF for Ele27: try with your ttH friends, otherwise let me know and I will contact other people.

**Comment by degrutto** [comment]
Hi Paolo,

it will be prescaled today...

the one to use is

HLT_Ele27_eta2p1_WPLoose_Gsf_v3 (2044276) 
https://cmswbm.web.cern.ch/cmswbm/cmsdb/servlet/HLTPath?PATHID=2044276

**Comment by bianchini** [comment]
Done by https://github.com/vhbb/cmssw/pull/445.
Closing
