### ISSUE TITLE
Crash in VBFlikelihood: make sure trigger names are fine

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#458]
@azzurrip, @chernyavskaya
Ciao,
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/VBFblikelihood.py#L67
makes the workflow crash because there is no more this trigger in TriggerTable: can you update the name?
Thanks

**Comment by azzurrip** [comment]
Hi, the names have changed as follows

“HLT_QuadPFJet_DoubleBTagCSV_VBF_Mqq200” => “HLT_QuadPFJet_BTagCSV_p016_p11_VBF_Mqq200”
“HLT_QuadPFJet_DoubleBTagCSV_VBF_Mqq240” => “HLT_QuadPFJet_BTagCSV_p016_p11_VBF_Mqq240”
"HLT_QuadPFJet_SingleBTagCSV_VBF_Mqq460” => "HLT_QuadPFJet_BTagCSV_p016_VBF_Mqq460”
"HLT_QuadPFJet_SingleBTagCSV_VBF_Mqq500” => "HLT_QuadPFJet_BTagCSV_p016_VBF_Mqq500”

On 14 Jun 2016, at 15:48, bianchini <notifications@github.com<mailto:notifications@github.com>> wrote:

@azzurriphttps://github.com/azzurrip, @chernyavskayahttps://github.com/chernyavskaya
Ciao,
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/VBFblikelihood.py#L67
makes the workflow crash because there is no more this trigger in TriggerTable: can you update the name?
Thanks

**Comment by bianchini** [comment]
Fixed by https://github.com/vhbb/cmssw/pull/454/commits/9bb07a97e2e525f1e8f4d5def85feb10c5f5ff75

**Comment by bianchini** [comment]
By the way... given that the MC does not contain a proper trigger emulation, can we rely on this logic:
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/VBFblikelihood.py#L67
to run the VBFblikelihood?

**Comment by azzurrip** [comment]
Indeed.  We still need to see in more detail how those HLT bits are filled in MC
(and if we can make any use of them). But for a first try we can leave the condition.

On 16 Jun 2016, at 09:07, bianchini <notifications@github.com<mailto:notifications@github.com>> wrote:

By the way... given that the MC does not contain a proper trigger emulation, can we rely on this logic:
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/VBFblikelihood.py#L67
to run the VBFblikelihood?

**Comment by bianchini** [comment]
Closing this issiue
