### ISSUE TITLE
double-b  retraining

### ISSUE THREAD

**Issue by cvernier** [vhbb/cmssw#585]
new training for double-b needed for Summer-16

**Comment by arizzi** [comment]
which samples? how many events?

**Comment by cvernier** [comment]
just need the recipe to include the latest training. https://twiki.cern.ch/twiki/bin/view/CMS/Hbbtagging#V4_training

**Comment by arizzi** [comment]
how about this:

  [image: Warning, important] Currently the V4 training is only provided
for AK8 jets.

**Comment by cvernier** [comment]
it's ok, as far as I know no analysis is using the CA15 jets. 
the old one is still valid for CA15.

**Comment by arizzi** [comment]
we do run CA15... are we really not using it @gkasieczka @ferencek ?

**Comment by ferencek** [comment]
Ideally, it would be nice if we had v4 training for CA15 jets as well. But since we don't, we'll have to stay with v3 for CA15 and switch to v4 for AK8. Note that the training files are explicitly defined in https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/test/combined_cmssw.py#L332-L344 so that needs to be updated in addition to following the recipe at https://twiki.cern.ch/twiki/bin/viewauth/CMS/Hbbtagging#V4_training

I also noticed that the input candidates for IPTagInfos in https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/test/combined_cmssw.py#L361 are incorrectly set (they should be set to the full collection of PF candidates, i.e. `particleFlow` for AOD and `packedPFCandidates` for MiniAOD).

**Comment by ferencek** [comment]
In addition, I guess https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/test/combined_cmssw.py#L671-L687 can be removed or commented out.

**Comment by arizzi** [comment]
it should be in fact converted into running deepCSV

**Comment by cvernier** [comment]
#602
