### ISSUE TITLE
Different type of MET

### ISSUE THREAD

**Issue by arizzi** [vhbb/cmssw#83]
Should we add different METs including
- MHT
- tkMET
- type1+2... etc..
- PuppiMET

?

**Comment by degrutto** [comment]
yes I would say yes

**Comment by arizzi** [comment]
code please :-)

**Comment by degrutto** [comment]
Hi Andrea,

I have the snippet ready and tested to add

metNoPu
tkMET
mht (pt>30)
and raw met (which was missing before)

but to add Puppimet a modification to METAnalyzer is needed (I already informed MRosaria about that)
how should I proceed with the commit?
Make two pulls requests (once for vhbb and one for heppy)? and if so what suffix/prefix for the branch to commit for the heppy one ?

btw, MVAmet is not yet in the miniAOD

**Comment by degrutto** [comment]
Hi Andrea,
see the next label.

Regarding the PuPPiMET it is fine if one instantiate the METAnalyzer with copyMETsByValue, which maybe is intended to be flagged when using different MET?
The problem is the current miniAOD we do not have all the met uncertainties filled for puppyMET hence it crashes when trying to fill those info in the miniAnalyzer,
and by raising copyMETsByValue, you do not do that.

**Comment by degrutto** [comment]
see https://github.com/vhbb/cmssw/pull/96
